---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
        version: "v1.0.0"
    spec:
      containers:
      - name: spring-boot
        image: kwonghung/springboot-oauth2-client:latest
        ports:
        - containerPort: 8080
        - containerPort: 8888
        env:
        - name: JAVA_TOOL_OPTIONS
          value: >-
            -Dcom.sun.management.jmxremote
            -Dcom.sun.management.jmxremote.port=8888
            -Dcom.sun.management.jmxremote.rmi.port=8889
            -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.ssl=false
        args:
          - "--spring.profiles.active=k8s"
        imagePullPolicy: Always
      - name: openjdk
        image: openjdk:11
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        imagePullPolicy: Always
        
