---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: nginx-gateway
  #namespace: istio-system
spec:
  # suppose the selector can reach the ingress-controller in istio-system space
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 81
      name: http
      protocol: HTTP
    hosts:
    - "default/*.istio-testbed.org.hk"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virt-svc
spec:
  hosts:
  - nginx.istio-testbed.org.hk
  gateways:
  #- "istio-system/nginx-gateway"
  - nginx-gateway
  exportTo: ["."]
  http:
  - route:
    - destination:
        host: nginx-service
        port:
          number: 8080
