---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
        version: "v1.0.0"
    spec:
      containers:
      - name: spring-boot
        image: kwonghung/springboot-oauth2-client:jdk8
        ports:
        - containerPort: 8080
        - containerPort: 1099
        args:
          - "--spring.profiles.active=k8s"
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
      - name: openjdk
        image: openjdk:8
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
        imagePullPolicy: Always
        
