---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-simple-webapp
  labels:
    app: springboot-simple-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-simple-webapp
  template:
    metadata:
      labels:
        app: springboot-simple-webapp
        version: "v1.0.0"
    spec:
      containers:
      - name: springboot-webapp
        image: kwonghung/springboot-simple-webapp:openjdk8
        ports:
        - containerPort: 8080
        - containerPort: 1099
        env:
        # both jmxremote.port and jmxremote.rmi.port properties should refer the same port therefore we only need to forward single port in k8s for JMX remote connection
        # the java.rmi.server.hostname property should be ip/hostname of the host that will run kubectl port-forward to forward the JMX remote port 
        - name: JAVA_TOOL_OPTIONS
          value: >-
            -Xms512m
            -Xmx1024m
            -Dcom.sun.management.jmxremote
            -Dcom.sun.management.jmxremote.authenticate=false
            -Dcom.sun.management.jmxremote.ssl=false
            -Dcom.sun.management.jmxremote.port=1099
            -Dcom.sun.management.jmxremote.rmi.port=1099
            -Djava.rmi.server.hostname=192.168.1.132
            -Dspring.jmx.enabled=true
        args:
          - "--spring.profiles.active=k8s"
        imagePullPolicy: Always
