---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: nginx
  namespace: default
spec:
  selector: {}
  jwtRules:
  - issuer: "https://dev-jkd6ttlt.us.auth0.com/oauth/token"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: nginx
  namespace: default
spec:
  selector: {}
