#
# A simple ServiceEntry can capture the traffic
# without the ServiceEntry, the request still can send out but will go through the PassthroughCluster 
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  labels:
    app: mysql-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-client
  template:
    metadata:
      labels:
        app: mysql-client
        version: v1
    spec:
      containers:
      - name: mysql-client
        image: mysql:8
        command: ["bash"]
        args: ["/root/mysql/traffic.sh"]
        volumeMounts:
        - name: mysql-script-vol
          mountPath: /root/mysql
      volumes:
      - name: mysql-script-vol
        configMap:
          name: mysql-script-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-script-configmap
data:
  traffic.sh: |-
    #!/bin/bash
    
    while :
    do
      mysql \
        -h 192.168.28.134 -P 3306 -D test \
        -u john -p'passw0rd' -e 'source /root/traffic.sql'
      sleep 1
    done
  traffic.sql: |-
    select current_time(), user(), database() from dual;
    show variables like 'version';
    show variables like 'hostname';
