---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-svc-entry
spec:
  hosts:
  - docker-mysql-v5.hung.org.hk
  location: MESH_INTERNAL
  ports:
  - number: 3306
    name: mysql
    protocol: TCP
  resolution: DNS
  workloadSelector:
    labels:
      database: mysql
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: mysql-v5-workload-entry
spec:      
  address: docker-mysql-v5.hung.org.hk
  weight: 80
  ports:
    mysql: 3306
  labels:
    database: mysql
    version: "5"
    platform: "docker"
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: mysql-v8-workload-entry
spec:
  address: docker-mysql-v8.hung.org.hk
  weight: 20
  ports:
    mysql: 3306
  weight: 10
  labels:
    database: mysql
    version: "8"
    platform: "docker"
