---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-client
  labels:
    app: http-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-client
  template:
    metadata:
      labels:
        app: http-client
        version: v1
    spec:
      containers:
      - name: http-client
        image: nicolaka/netshoot
        command: ["bash"]
        args: ["/root/test/ping.sh"]
        volumeMounts:
        - name: test-script-vol
          mountPath: /root/test
      volumes:
      - name: test-script-vol
        configMap:
          name: test-script-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-script-configmap
data:
  ping.sh: |-
    #!/bin/bash
    
    while :
    do
      curl -svk https://tomcat.hung.org.hk:8443/echo.html
      sleep 1
    done

