---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: tomcat-service-entry
spec:
  hosts:
  - tomcat.hung.org.hk
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: http
    protocol: HTTP
  resolution: DNS
  workloadSelector:
    labels:
      app: tomcat
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: tomcat7-node01
spec:      
  address: docker-node01.hung.org.hk
  ports:
    http: 8080
  labels:
    app: tomcat
    version: "7"
    platform: docker
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: tomcat7-node02
spec:
  address: docker-node02.hung.org.hk
  ports:
    http: 8080
  labels:
    app: tomcat
    version: "7"
    platform: docker
