---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: tomcat-service-entry
spec:
  hosts:
  - tomcat.hung.org.hk
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: http
    protocol: HTTP
  - number: 8443
    name: https
    protocol: HTTPS
  resolution: STATIC
  workloadSelector:
    labels:
      app: tomcat
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: enable-mutual-for-hung-org-hk
spec:
  host: *.hung.org.hk
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
