---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: http-service-entry
  namespace: default
spec:
  hosts:
  - http-svc.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: STATIC
  endpoints:
  - address: 192.168.1.163
    network: vm-network
    serviceAccount: vm-operator
    ports:
      http: 80
      https: 443
    
