---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: http-sample
  namespace: default
spec:
  hosts:
  - http-svc.default.svc.cluster.local
  tcp:
  - route:
    - destination:
        host: tomcat.hung.org.hk
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: http-service-entry
spec:
  hosts:
  - http-svc.default.svc.cluster.local
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: http
    protocol: HTTP
  - number: 8443
    name: https
    protocol: HTTPS
  resolution: STATIC
  workloadSelector:
    labels:
      app: tomcat
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mtls-for-hung-org-hk
spec:
  host: "*.hung.org.hk"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
