---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: tomcat-service-entry
spec:
  hosts:
  - tomcat.hung.org.hk
  location: MESH_INTERNAL
  ports:
  - number: 8080
    name: rest
    protocol: HTTP
  - number: 8443
    name: rest-https
    protocol: HTTPS
  resolution: STATIC
  workloadSelector:
    labels:
      app: tomcat
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tomcat-dest-rule
spec:
  host: tomcat.hung.org.hk
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      sni: tomcat.hung.org.hk
