apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "ext-apache"
  namespace: "default"
spec:
  metadata:
    labels:
      app: "ext-apache"
  template:
    serviceAccount: "vm-apache"
    network: "vm-network"
  probe:
    initialDelaySeconds: 1
    periodSeconds: 600
    httpGet:
      port: 8080

    
 
