#
# A simple ServiceEntry can capture the traffic
# without the ServiceEntry, the request still can send out but will go through the PassthroughCluster 
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  labels:
    app: mysql-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-client
  template:
    metadata:
      labels:
        app: mysql-client
        version: v1
    spec:
      containers:
      - name: mysql-client
        image: mysql:8
        command: ["mysql"]
        args: ["-h","192.168.28.130","-P","3306","-D","test","-u","john","-ppassw0rd","-e","'source /root/traffic.sql'"]
---
