#
# A simple ServiceEntry can capture the traffic
# without the ServiceEntry, the request still can send out but will go through the PassthroughCluster 
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-app
  labels:
    app: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
        version: v1
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["watch"]
        args: ["-n","1","curl","-v","https://raw.githubusercontent.com/kwonghung-YIP/istio-testbed/main/service-entry/test.txt"]
---
