---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: mysql
spec:
  address: 192.168.28.130
  labels:
    database: mysql
    class: docker
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql
spec:
  hosts:
  - mysql-server
  location: MESH_INTERNAL
  ports:
  - number: 3306
    name: mysql
    protocol: TCP
  resolution: STATIC
  workloadSelector:
    labels:
      database: mysql
