---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mysql-virt-svc
spec:
  hosts:
  - 192.168.28.130
  tcp:
  - route:
    - destination:
        host: mysql-server
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-svc-entry
spec:
  hosts:
  - mysql-server
  location: MESH_INTERNAL
  ports:
  - number: 3306
    name: mysql
    protocol: TCP
  resolution: NONE
  workloadSelector:
    labels:
      database: mysql
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: mysql-workload-entry-v8
spec:
  address: 192.168.28.130
  ports:
    mysql: 3306
  labels:
    database: mysql
    version: "8"
    runtime: docker
---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: mysql-workload-entry-v5
spec:
  address: 192.168.28.130
  ports:
    mysql: 3307
  labels:
    database: mysql
    version: "5"
    runtime: docker
